language: java
before_install:
  - chmod +x gradlew
script:
  - ./gradlew build --info
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
deploy:
  provider: heroku
  api_key:
    secure: y8VMyEDbYZWuGupsOKXA0SPULzusMe6oQVpi/lzsKGcffcxyY3Uo5liZGsAUiGcGVEXokQVtDkHt9QDI+VxOqe9ipz4j1SWqJ0V/btddjpI3QVxVL7h3X7aZ7TKY0de5O4CodJAGqbW4RGojGYad3KIt/K+yauihmWDc1F208A8dRDgGN59JN2TUWppdFIbXc6A1z3kZdgxV/Au5cydi4chlIfemVWKInOvbvVi59pwIvKxx1JVTpuFINYvkc2MOi7c+qLr/VujFOFReTOgm7SpWTKPhm671EXeqRKQ9aEyo8au0c9Z8iYaRNAbcEJTBPZXd10xySSp+Jt8zbXyeDpFysf4DYzkZe/TK2pXwnmFM99qbRLZlYCdq0EW0JVpHLl2mwihYnmMeoqkxsZeKE8ope6EiT5AUHrSXByuYHVIdjpE9Od+cgJtglIqcbagcWoZ16/zWvdaZp8bJSdJlYFChHBWMsmmOtN8P3T18M5c2yaMXrO/nvYDtX2PAzNCzlzrYNjwuZTsA21SzTG1A2zoVCg7ekz+QJQDRu0PEuvnS/SNBIhooyvfqX3IWMZMXyH1YCHZqiPTB5Tu98WQoPH4eE5Hdv18GKg4O7rxhCRsSxMy4zrWx9EWrYnecsEHlwPrJvh2QbC/0O4vWxTtayKRoIgLvZmtWCwBZAOo27Mc=
  app: phabpharmacy
  skip_cleanup: true